Desktop/Ping/Ping/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from dashboard import views
from . import settings

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/Ping/dashboard/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^register/$', views.register, name='register'),
    url(r'^post/$', views.post, name='post'),
    url(r'^profile/$', views.profile_page, name='profile_page'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^(?P<post_id>[0-9]+)/saved/$', views.saved, name='saved'),
    url(r'^(?P<post_id>[0-9]+)/comment/$', views.comment, name='comment'),
]

Desktop/Ping/dashboard/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django import forms

# Create your models here.
class Post(models.Model):
    post_pic = models.ImageField()
    post_text = models.TextField(max_length=140)
    time = models.DateTimeField(auto_now_add=True)
    post_by = models.ForeignKey(User, default=1)
    saved = models.BooleanField(default=False)

    def __str__(self):
        return (str(self.post_by) + ' - ' + str(self.post_text))

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    comment_text = models.TextField(max_length=140)
    comment_by = models.ForeignKey(User, related_name='comments')

    def __str__(self):
        return (str(self.comment_by) + ' - ' + str(self.comment_text))

    def total(self):
        return self.Comment.all().count()

Desktop/Ping/dashboard/forms.py
from django import forms

from .models import Post, Comment, User

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_pic', 'post_text']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['comment_text']

Desktop/Ping/dashboard/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import PostForm, CommentForm, UserForm
from .models import Post, Comment, User

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

# Create your views here.
def index(request):
    return render(request, 'dashboard/index.html')

def dashboard(request):
    if not request.user.is_authenticated():
        return render(request, 'dashboard/index.html')
    else:
        posts = Post.objects.all().order_by('-time')
        user = request.user
        query = request.GET.get("data")
        if query:
            posts = posts.filter(
                Q(post_by__icontains=query)
            ).distinct()
            return render(request, 'dashboard/dashboard.html', {
                'posts': posts,
                'user': user,
            })
        else:
            return render(request, 'dashboard/dashboard.html', {'posts': posts, 'user': user})

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                posts = Post.objects.all().order_by('-time')
                comments = Comment.objects.all()
                user = request.user
                return render(request, 'dashboard/dashboard.html', {'posts': posts, 'comments': comments, 'user': user})
            else:
                return render(request, 'dashboard/index.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'dashboard/index.html', {'error_message': 'Invalid login'})
    return render(request, 'dashboard/index.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'dashboard/index.html', context)

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                posts = Post.objects.all()
                return render(request, 'dashboard/dashboard.html', {'posts': posts})
    context = {
        "form": form,
    }
    return render(request, 'dashboard/register.html', context)

def post(request):
    if not request.user.is_authenticated():
        return render(request, 'dashboard/index.html')
    else:
        form = PostForm(request.POST or None, request.FILES or None)
        user = request.user
        if form.is_valid():
            post = form.save(commit=False)
            post.post_by = request.user
            post.post_pic = request.FILES['post_pic']
            file_type = post.post_pic.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'user': user,
                    'post': post,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'dashboard/post.html', context)
            post.save()
            posts = Post.objects.all().reverse()
            return render(request, 'dashboard/dashboard.html', {'posts': posts})
        context = {
            "form": form,
        }
        return render(request, 'dashboard/post.html', context)

def profile_page(request):
    if not request.user.is_authenticated():
        return render(request, 'dashboard/index.html')
    else:
        user = request.user
        post_number = Post.objects.filter(post_by=request.user).count()
        posts = Post.objects.filter(post_by=request.user)
        if post_number == 0:
            post_message = 'You have no posts! Please add some.'
        else:
            post_message = 'You have total ' + str(post_number) + ' post(s).'
        context = {'user': user, 'post_message': post_message, 'posts': posts}
        return render(request, 'dashboard/profile_page.html', context)

def settings(request):
    if not request.user.is_authenticated():
        return render(request, 'dashboard/index.html')
    else:
        #yet to be added
        return render(request, 'dashboard/dashboard.html')

def saved(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.saved:
        post.saved = False
    else:
        post.saved = True
    post.save()
    posts = Post.objects.all()
    comments = Comment.objects.all()
    context = {
        'posts': posts,
        'comments': comments,
    }
    return render(request, 'dashboard/dashboard.html', context)

def comment(request, post_id):
    if not request.user.is_authenticated():
        return render(request, 'dashboard/index.html')
    else:
        post = get_object_or_404(Post, pk=post_id)
        comments = Comment.objects.filter(post=post)
        return render(request, 'dashboard/comment.html', {'post': post, 'comments': comments})

Desktop/Ping/dashboard/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <title>{% block title %}BMU Ping{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/main.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/profile_page.css' %}"/>
    <link rel="shortcut icon" href="{% static 'dashboard/img/Ping.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-inverse navbar-custom bg-dark">
    <div class="container">
  <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}"><img src="{% static 'dashboard/img/PingAlt.png' %}" class="img-responsive" width="50"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'dashboard:dashboard' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" value="{{ request.GET.data }}">
      <button class="btn btn-sm btn-search my-2 my-sm-0" type="submit">Search</button>
    </form>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
          <a class="nav-link" href="{% url 'dashboard:post' %}">Post</a>
      </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#">Message</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          @{{ user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'dashboard:profile_page' %}">Profile</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'dashboard:logout_user' %}">Logout</a>
        </div>
      </li>
    </ul>
  </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Desktop/Ping/dashboard/templates/dashboard/comment.html
{% extends 'dashboard/base.html' %}
{% block title %} Comment {% endblock %}
{% block body %}
<div class="container">
    <form class="row" style="margin-top: 50px;">
        <div class="col-lg-8 col-sm-12">
            <img src="{{ post.post_pic.url }}" class="img-responsive" style="width: 100%; height: 100%;"/>
        </div>
        <div class="col-lg-4 col-sm-12">
            <h5>{{ post.post_by }}'s post</h5>
            <p>{{ post.post_text }}</p>
            <p>
                {% if post.saved %}
                    <em>#saved</em>
                {% endif %}
            </p>
            {% if comments %}
                {% for comment in comments %}
                    <h6>{{ comment.comment_by }}:</h6> <p>{{ comment.comment_text }}</p>
                {% endfor %}
            {% else %}
                <h6> No comments yet! Be the first one to comment. </h6>
            {% endif %}
            <br />
            <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
             <div class="form-group">
                <label for="comment">Add your comment: </label>
                <textarea class="form-control" id="comment" rows="3"></textarea>
             </div>
            <button type="submit" class="btn btn-lg btn-settings">Submit</button>
            </form>
    </div>
</div>
{% endblock %}

Desktop/Ping/dashboard/templates/dashboard/dashboard.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}
{% block title %} Dashboard {% endblock %}
{% block body %}
<div class="container">
    {% for post in posts %}
        <div class="row card-row">
            <div class="col-lg-8">
            <div class="card" style="width: 100%;">
              <img class="card-img-top" src="{{ post.post_pic.url }}" alt="[Image not displayed!]">
              <div class="card-body">
                <h6 class="card-title">@{{ post.post_by }}</h6>
                <p class="card-text">{{ post.post_text }}<br/>[{{  post.time.time  }}] {{ post.time.date }}</p>
                <a href="{% url 'dashboard:saved' post.id %}"><i class="fa fa-2x {% if post.saved %}fa-thumb-tack{% endif %}"></i></a>&nbsp;
                  <a href="{% url 'dashboard:comment' post.id %}"><i class="fa fa-2x fa-comment-o" aria-hidden="true"></i></a>
              </div>
            </div>
        </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

Desktop/Ping/dashboard/templates/dashboard/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

Desktop/Ping/dashboard/templates/dashboard/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <title>{% block title %}Ping | Log In{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/main.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/index.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Eagle+Lake" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'dashboard/img/Ping.png' %}" type="image/x-icon">
</head>
<body id="body-image">
<div class="container">
    <div class="row brand" style="margin-top: 50px;">
        <div class="col-lg-12">
            <center><h1>Ping</h1></center>
        </div>
    </div>
    <div class="row" style="margin-top: 100px;">
        <div class="col-lg-8 col-sm-12">
            <img src="{% static 'dashboard/img/Ping.png' %}" class="img-responsive">
        </div>
        <div class="col-lg-4 col-sm-12">
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <form class="form-horizontal" role="form" action="{% url 'dashboard:login_user' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <div>
                <input id="id_username" maxlength="30" name="username" type="text" placeholder="Username">
            </div>
        </div>
        <div class="form-group">
            <div>
                <input id="id_password" maxlength="30" name="password" type="password" placeholder="Password">
            </div>
        </div>
        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-search">Log In</button>
            </div>
        </div>
    </form>
    <p>Don't have an account? <a href="{% url 'dashboard:register' %}">Click here</a> to register.</p>
    </div>
    </div>
</div>
</body>
</html>

Desktop/Ping/dashboard/templates/dashboard/post.html
{% extends 'dashboard/base.html' %}
{% block title %} Post {% endblock %}
{% block body %}
<div class="container" style="margin-top: 50px;!important">
    <div class="row">
        <div class="col-sm-12 col-md-7">
                    <h3>What's on your mind?</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'dashboard/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

        </div>
    </div>
</div>
{% endblock %}

Desktop/Ping/dashboard/templates/dashboard/profile.html
{% extends 'dashboard/base.html' %}

Desktop/Ping/dashboard/templates/dashboard/profile_page.html
{% extends 'dashboard/base.html' %}
{% block title %} Profile | {{ user.username }} {% endblock %}
{% block body %}
<div class="container">
    <div class="row" style="margin-top: 50px;">
        <div class="col-lg-4 col-sm-9">
            <h3>{{ user.username }}'s profile</h3>
            <h6>{{ user.email }}</h6><br />
            <p>{{ post_message }}</p>
        </div>
        <div class="ml-auto col-lg-4 offset-lg-4 col-sm-3">
            <button type="button" class="btn btn-lg btn-danger btn-settings"><a href="{% url 'dashboard:settings' %}"><i class="fa fa-wrench"></i></a></button>
        </div>
    </div>
    <div class="row" style="margin-top: 20px;">
        {% for post in posts %}
            <div class="col-lg-4 col-sm-12 picture">
                <a href="{% url 'dashboard:comment' post.id %}"><img src="{{ post.post_pic.url }}" class="img-responsive" style="width: 100%; height: 100%;"/></a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Desktop/Ping/dashboard/templates/dashboard/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <title>{% block title %}Ping | Register{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/main.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'dashboard/register.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Eagle+Lake" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'dashboard/img/Ping.png' %}" type="image/x-icon">
</head>
<body>
<div class="container brand" style="margin-top: 100px;">
    <center><h1>Join millions of other Travellers!</h1>
    <img src="{% static 'dashboard/img/Ping.png' %}" class="img-responsive">
        </center>
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}
    <center>
    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'dashboard/form_template.html' %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-search">Register</button>
            </div>
        </div>
    </form>
    <p>Already have an account? <a href="{% url 'dashboard:login_user' %}">Click here</a> to log in.</p>
    </center>
</div>
<script>
    $( document ).ready(function() {

    scaleVideoContainer();

    initBannerVideoSize('.video-container .poster img');
    initBannerVideoSize('.video-container .filter');
    initBannerVideoSize('.video-container video');

    $(window).on('resize', function() {
        scaleVideoContainer();
        scaleBannerVideoSize('.video-container .poster img');
        scaleBannerVideoSize('.video-container .filter');
        scaleBannerVideoSize('.video-container video');
    });

});

function scaleVideoContainer() {

    var height = $(window).height() + 5;
    var unitHeight = parseInt(height) + 'px';
    $('.homepage-hero-module').css('height',unitHeight);

}

function initBannerVideoSize(element){

    $(element).each(function(){
        $(this).data('height', $(this).height());
        $(this).data('width', $(this).width());
    });

    scaleBannerVideoSize(element);

}

function scaleBannerVideoSize(element){

    var windowWidth = $(window).width(),
    windowHeight = $(window).height() + 5,
    videoWidth,
    videoHeight;

    // console.log(windowHeight);

    $(element).each(function(){
        var videoAspectRatio = $(this).data('height')/$(this).data('width');

        $(this).width(windowWidth);

        if(windowWidth < 1000){
            videoHeight = windowHeight;
            videoWidth = videoHeight / videoAspectRatio;
            $(this).css({'margin-top' : 0, 'margin-left' : -(videoWidth - windowWidth) / 2 + 'px'});

            $(this).width(videoWidth).height(videoHeight);
        }

        $('.homepage-hero-module .video-container video').addClass('fadeIn animated');

    });
}
</script>
</body>
</html>

Desktop/Ping/dashboard/templates/dashboard/settings.html
{% extends 'dashboard/base.html' %}
{% block title %}Settings{% endblock %}
{% block body %}

{% endblock %}